
# Configure a default setup of Home Assistant (frontend, api, etc)

default_config:

# Text to speech

tts:
  - platform: google_cloud
    key_file: googlecloud.json
    voice: fr-FR-Wavenet-E
    encoding: linear16
    speed: 1.2
    pitch: -2.5
    gain: 5.0

logger:
  default: notset

http:
  cors_allowed_origins:
    - https://hooks.nabu.casa

shell_command: !include shellcommand.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
